//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManager
    {
        public int ManagerId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Sector { get; set; }
        public string AccessLevel { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
